### ISSUE TITLE
vue3+vite3.x+ts项目打包完成后报错

### ISSUE THREAD

**Issue by ysg-lijinwen** [vbenjs/vite-plugin-svg-icons#110]
rendering chunks (113)...
 ERROR  [vite:esbuild-transpile] Transform failed with 1 error:                                                                20:40:00  
assets/js/virtual_svg-icons-register-f87e325e.js:82032:18: ERROR: Transforming async generator functions to the configured target environment ("chrome64", "edge79", "es2020", "firefox67", "safari11.1" + 2 overrides) is not supported yet

Transforming async generator functions to the configured target environment ("chrome64", "edge79", "es2020", "firefox67", "safari11.1" + 2 overrides) is not supported yet
82030|  };
82031|
82032|  const readBytes = async function* (iterable, chunkSize, encode) {
   |                    ^
82033|    for await (const chunk of iterable) {
82034|      yield* streamChunk(ArrayBuffer.isView(chunk) ? chunk : (await encode(String(chunk))), chunkSize);

 ERROR  error during build:                                                                                                    20:40:00  
Error: Transform failed with 1 error:
assets/js/virtual_svg-icons-register-f87e325e.js:82032:18: ERROR: Transforming async generator functions to the configured target environment ("chrome64", "edge79", "es2020", "firefox67", "safari11.1" + 2 overrides) is not supported yet
    at failureErrorWithLog (E:\CarleaData\git\project\sjsy\web\node_modules\esbuild\lib\main.js:1575:15)
    at E:\CarleaData\git\project\sjsy\web\node_modules\esbuild\lib\main.js:814:29
    at responseCallbacks.<computed> (E:\CarleaData\git\project\sjsy\web\node_modules\esbuild\lib\main.js:680:9)
    at handleIncomingPacket (E:\CarleaData\git\project\sjsy\web\node_modules\esbuild\lib\main.js:735:9)
    at Socket.readFromStdout (E:\CarleaData\git\project\sjsy\web\node_modules\esbuild\lib\main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by 335060087** [comment]
解决了吗

**Comment by yangxu52** [comment]
@ysg-lijinwen This is related to esbuild. It's 'async generator function' syntax Grammar downgrade failure.
you may try to polyfill this syntax, or try to sue `vite-plugin-legacy` or use `babel`

Then,
you can try the maintaining version by me: [vite-plugin-svg-icons-ng](https://github.com/yangxu52/vite-plugin-svg-icons-ng).
