### ISSUE TITLE
vite + ts打包时报错Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Cheng-x-c** [vbenjs/vite-plugin-svg-icons#43]
[vite:svg-icons] Could not load D:/IdeaProjects/blog/vue3-vite-ts-blog/index.html: Cannot read property 'replace' of undefined
error during build:
TypeError: Could not load D:/IdeaProjects/blog/vue3-vite-ts-blog/index.html: Cannot read property 'replace' of undefined
    at compilerIcon (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\vite-plugin-svg-icons\dist\index.js:5316:21)
    at async getSymbol (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\vite-plugin-svg-icons\dist\index.js:5282:21)
    at async compilerIcons (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\vite-plugin-svg-icons\dist\index.js:5294:9)
    at async createModuleCode (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\vite-plugin-svg-icons\dist\index.js:5233:33)
    at async Object.load (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\vite-plugin-svg-icons\dist\index.js:5203:31)
    at async D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\rollup\dist\shared\rollup.js:22176:83
    at async Queue.work (D:\IdeaProjects\blog\vue3-vite-ts-blog\node_modules\rollup\dist\shared\rollup.js:21759:32)

**Comment by Cheng-x-c** [comment]
![image](https://user-images.githubusercontent.com/59717369/151684272-fe2462a5-b216-447e-ba26-18d55437f3e9.png)
![image](https://user-images.githubusercontent.com/59717369/151684277-6e011bc5-a1b2-4087-888e-5aa2a71581e2.png)

**Comment by boai92** [comment]
> 我也遇到了，应该是版本问题 将package.json -> devDependencies -> "vite-plugin-svg-icons": "1.0.5", 另外 npm install vite-plugin-svg-icons@1.0.5 就可以了！

我升级了版本也没用呢
