### ISSUE TITLE
fast-glob issue

### ISSUE THREAD

**Issue by 719media** [vbenjs/vite-plugin-svg-icons#44]
when upgrading from eslint 7 to eslint 8, I ran into an issue with this library requiring fast-glob, and it not being in dependencies. I didn't see that the install instructions indicated that fast-glob needed to be installed. So it was throwing errors when compiling. Perhaps put fast-glob into dependencies so that it will work with setups without other libraries including fast-glob

**Comment by cn-troy** [comment]
me too. cannot find module 'fast-glob'
![image](https://user-images.githubusercontent.com/4318293/152922744-4bfe1105-aa0f-43e2-84d1-eeb8defbcbb7.png)

**Comment by YUN-RU-TSENG** [comment]
me too
```
failed to load config from /Users/yunru/Documents/work/koloko_liff2/vite.config.js
error when starting dev server:
Error: Cannot find module 'fast-glob'
Require stack:
- /Users/yunru/Documents/work/koloko_liff2/node_modules/vite-plugin-svg-icons/dist/index.cjs
- /Users/yunru/Documents/work/koloko_liff2/vite.config.js
- /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/chunks/dep-76613303.js
- /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/cli.js
- /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/yunru/Documents/work/koloko_liff2/node_modules/vite-plugin-svg-icons/dist/index.cjs:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .js] (/Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/chunks/dep-76613303.js:75145:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

```

**Comment by YUN-RU-TSENG** [comment]
> me too
> 
> ```
> failed to load config from /Users/yunru/Documents/work/koloko_liff2/vite.config.js
> error when starting dev server:
> Error: Cannot find module 'fast-glob'
> Require stack:
> - /Users/yunru/Documents/work/koloko_liff2/node_modules/vite-plugin-svg-icons/dist/index.cjs
> - /Users/yunru/Documents/work/koloko_liff2/vite.config.js
> - /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/chunks/dep-76613303.js
> - /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/cli.js
> - /Users/yunru/Documents/work/koloko_liff2/node_modules/vite/bin/vite.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/yunru/Documents/work/koloko_liff2/node_modules/vite-plugin-svg-icons/dist/index.cjs:5:12)
>     at Module._compile (node:internal/modules/cjs/loader:1097:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
>     at Object.require.extensions.<computed> [as .js] (/Users/yunru/Documents/work/koloko_liff2/node_modules/vite/dist/node/chunks/dep-76613303.js:75145:13)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> ```

```
 "vue": "^3.2.25",
  "vue-router": "^4.0.12",
  "vuex": "^4.0.2",
  "yup": "^0.32.11"
```

**Comment by whidy** [comment]
I try to install `fast-glob` by myself, it runs ok now. Maybe not a good solution, but can fix the error at least.

**Comment by itsnwa** [comment]
> I try to install `fast-glob` by myself, it runs ok now. Maybe not a good solution, but can fix the error at least.

Wow, it worked 😅 Thanks! Yeah, would be nice with a proper fix 👍

**Comment by JiangBingLong** [comment]
npm install fast-glob

**Comment by pxyi** [comment]
俺也一样
```
failed to load config from /Users/edy/Desktop/m.chunjuan/vite.config.ts
error when starting dev server:
Error: Cannot find module 'fast-glob'
Require stack:
- /Users/edy/Desktop/m.chunjuan/node_modules/.pnpm/vite-plugin-svg-icons@2.0.1_vite@3.1.0/node_modules/vite-plugin-svg-icons/dist/index.cjs
- /Users/edy/Desktop/m.chunjuan/vite.config.ts
- /Users/edy/Desktop/m.chunjuan/node_modules/.pnpm/vite@3.1.0_sass@1.54.9/node_modules/vite/dist/node/chunks/dep-665b0112.js
```

**Comment by yangxu52** [comment]
@719media @cn-troy @YUN-RU-TSENG @whidy @itsnwa @JiangBingLong @pxyi 
You can try the maintaining version by me: [vite-plugin-svg-icons-ng](https://github.com/yangxu52/vite-plugin-svg-icons-ng).

the 'fast-global'  been built-in

**Comment by tedw** [comment]
Still seeing this:

```
Error: vite-plugin-svg-icons tried to access fast-glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by yangxu52** [comment]
> Still seeing this:
> 
> ```
> Error: vite-plugin-svg-icons tried to access fast-glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> ```

Use `vite-plugin-svg-icons-ng` to instead of it. behavior consistency, more fastly, less bugs.
